#!/bin/sh
: ${XARGS?Please set XARGS environment variable}
# When the utility exits with exit status 255


# Only runs utility once.
res=$(echo foo bar baz |
  $XARGS -n 1 sh -c 'echo "$@"; exit 255' xyzzy 2> /dev/null)
case $res in
  ('foo') ;;
  (*) exit 9 ;;
esac

# Has some stderr.
res=$(echo foo bar baz |
  $XARGS -n 1 sh -c 'echo "$@"; exit 255' xyzzy 2>&1 >/dev/null)
case $res in
  ('') exit 8 ;;
  (*) ;;
esac

printf '%s\n' "$0 passed"
