#!/bin/sh
: ${XARGS?Please set XARGS environment variable}

#Interaction of -n and -s

res=$(yes foo | sed 99q | $XARGS -s 99 -n 55 echo | awk '{print length($0)}')
for length in $res
do
  if [ $length -ge 99 ]
  then
    exit 9
  fi
done

printf '%s\n' "$0 passed"
