#!/bin/sh
: ${XARGS?Please set XARGS environment variable}

# Interaction of -n and -s

len=99
res=$(yes foo | sed ${len}q | $XARGS -s $len -n $(($len / 2)) echo | awk '{print length($0)}')
for length in $res
do
  if [ $length -ge $len ]
  then
    exit 9
  fi
done

printf '%s\n' "$0 passed"
